#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Paper Research Prompts - 学术论文研究提示词模板

@Time    : 2024
@Author  : MetaGPT Extension
@File    : paper_research_prompts.py
"""

PAPER_RESEARCH_SYSTEM_PROMPT = """You are an academic paper researcher. Your goal is to help users efficiently search, analyze, and summarize academic papers.

Your capabilities:
1. Search for relevant papers from Semantic Scholar and arXiv
2. Fetch detailed information about each paper
3. Generate comprehensive summaries and key points
4. Analyze citation relationships and research impact
5. Rank papers by relevance, citations, or recency
6. Provide reading recommendations

You should always:
- Provide accurate and well-structured information
- Cite sources properly
- Be concise but comprehensive
- Prioritize recent and high-impact papers
"""

PAPER_SEARCH_PROMPT = """
## Task
Search for academic papers related to: {topic}

## Search Configuration
- Maximum results: {max_results}
- Year range: {year_range}
- Minimum citations: {min_citations}
- Language: {language}

## Requirements
1. Search across multiple academic databases (Semantic Scholar, arXiv)
2. Filter papers by relevance to the topic
3. Return papers with key metadata: title, authors, year, venue, citations
4. Prioritize recent papers and papers with high citation counts
"""

PAPER_SUMMARY_PROMPT = """
## Paper Information
- **Title**: {title}
- **Authors**: {authors}
- **Year**: {year}
- **Venue**: {venue}
- **Citations**: {citation_count}

## Abstract
{ abstract}

## Requirements
Provide a comprehensive summary in {language} including:
1. **Core Contribution**: Main contribution of the paper
2. **Methodology**: Methods or approaches used
3. **Key Findings**: Most important results
4. **Highlights**: Standout aspects
5. **Limitations**: Potential limitations

Length: 300-500 words.
"""

PAPER_REPORT_TEMPLATE = """
# Academic Paper Research Report

**Topic**: {topic}
**Date**: {date}
**Papers Found**: {count}

---

## Summary
{summary}

## Papers
{papers}

## Reading Recommendations
{recommendations}

---
*Generated by PaperResearcher*
"""

COMPARATIVE_ANALYSIS_PROMPT = """
## Papers to Compare
{papers_info}

## Requirements
Provide a comparative analysis in {language}:
1. **Overview**: Brief description of each paper (1-2 sentences)
2. **Similarities**: Common themes or approaches
3. **Differences**: Methodological differences
4. **Complementary Aspects**: How papers complement each other
5. **Comparison Table**: Method, Scope, Results, Limitations

Use a structured format with clear sections.
"""

CITATION_ANALYSIS_PROMPT = """
## Paper
- **Title**: {title}
- **Authors**: {authors}
- **Citations**: {citations}

## Citation Network
{network}

## Requirements
Analyze the citation network and provide:
1. **Impact Assessment**: Academic impact based on citations
2. **Key References**: Most influential papers in references
3. **Follow-up Research**: Trends in papers citing this work
4. **Research Gaps**: Areas not yet explored
"""

__all__ = [
    "PAPER_RESEARCH_SYSTEM_PROMPT",
    "PAPER_SEARCH_PROMPT",
    "PAPER_SUMMARY_PROMPT",
    "PAPER_REPORT_TEMPLATE",
    "COMPARATIVE_ANALYSIS_PROMPT",
    "CITATION_ANALYSIS_PROMPT",
]
